[package]
name = "s4-vaultify"
version = "0.1.0"
authors = ["matevl <144525314+matevl@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.0", features = [] }
<<<<<<< HEAD
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
bcrypt = "0.12"
rand = "0.9.0"
=======
rand = "0.8.5"
>>>>>>> 1855d9e (open file in bin + save + rand namegen for bin)

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
