[package]
name = "s4-vaultify"
version = "0.1.0"
authors = ["matevl <144525314+matevl@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.0", features = [] }
web-sys = { version = "0.3.77", features = ["HtmlTextAreaElement","Window", "Blob", "Url", "Document","Navigator","Clipboard"] }
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"
regex = "1.11.1"
wasm-bindgen-futures = "0.4.50"
gloo-timers = { version = "0.3"}

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
