[package]
name = "s4-vaultify"
version = "0.1.0"
authors = ["matevl <144525314+matevl@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.0", features = [] }
rand = "0.9"
infer = "0.19"
kamadak-exif = "0.6.1"
ffmpeg-next = "7.1.0"
tempfile = "3.16.0"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
