[package]
name = "serverback"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.0.1"
serde = { version = "1.0", features = ["derive"] }
s4-vaultify = {path = "../"}
serde_json = "1.0.139"
lazy_static = "1.5.0"
spin = "0.9.8"