[package]
name = "serverback"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.0.1"
serde = { version = "1.0", features = ["derive"] }
s4-vaultify =  {path = "../"}
account = {path = "../src/account_manager/account.rs"}
serde_json = "1.0.139"