name: Build and Test Pull Requests to Master

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libgtk-3-dev \
            libgdk-pixbuf2.0-dev \
            libcairo2-dev \
            libatk1.0-dev \
            libpango1.0-dev \
            libglib2.0-dev \
            meson ninja-build \
            libgtk-3-dev \
            pkg-config \
            libgdk-pixbuf2.0-dev \
            javascriptcoregtk-4.1-dev \
            libsoup-3.0-dev \
            webkit2gtk-4.1-dev \
            libxdo3

      - name: Set PKG_CONFIG_PATH
        run: |
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Build project
        run: cargo build --release

      - name: Run tests
        run: cargo test
